[tool.ruff]
target-version = "py39"  # 告诉 Ruff 你项目的 Python 版本（≥3.9 才能用 list[...] 语法）
line-length = 120  # 代码最大行宽
select = [         # 选择的规则
    "F",
    "E",
    "W",
    "UP",
]
fixable = ["ALL"]
ignore = ["F401", "F841", "W291"]   # 忽略的规则